variables:
  ARTIFACTS: "."
  RANCHER_URL: "http://192.168.33.10"
  GIT_SSL_NO_VERIFY: "1"    # you normally SHOULD NOT do this

stages:
  - build
  - build_image
  - deploy_prod

build_job:
  stage: build
  tags:
    - docker
  image: node:8.6.0-alpine
  before_script:
    - npm -v
  script:
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - $ARTIFACTS

build_image_job:
  stage: build_image
  tags:
    - docker
  image: docker:17.06.2-ce
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
    - docker tag $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_prod_job:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy_prod
  environment:
    - name: production
  tags:
    - docker
  only:
    - master
  script:
    - upgrade --new-image $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID --environment production --stack devspace --service TodoApi


